// <auto-generated />
using System;
using Europiyum.Cms.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Europiyum.Cms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CmsDbContext))]
    [Migration("20260404233451_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultLanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("HomepageVariantKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrimaryDomain")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DefaultLanguageId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.CompanyLanguage", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("CompanyId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("company_languages", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.ComponentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonPayload")
                        .HasColumnType("text");

                    b.Property<int?>("PrimaryMediaId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ComponentTypeId");

                    b.HasIndex("PrimaryMediaId");

                    b.ToTable("component_items", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.ComponentTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyHtml")
                        .HasColumnType("text");

                    b.Property<string>("ButtonText")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ButtonUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("ComponentItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("text");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ComponentItemId", "LanguageId")
                        .IsUnique();

                    b.ToTable("component_translations", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("component_types", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.FormDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Key")
                        .IsUnique();

                    b.ToTable("form_definitions", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.FormField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultLabel")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("FieldType")
                        .HasColumnType("integer");

                    b.Property<int>("FormDefinitionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FormDefinitionId");

                    b.ToTable("form_fields", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.FormSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubmitterIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FormDefinitionId");

                    b.ToTable("form_submissions", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.HomePageSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("LinkedComponentItemId")
                        .HasColumnType("integer");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinkedComponentItemId");

                    b.HasIndex("CompanyId", "SectionKey", "SortOrder");

                    b.ToTable("home_page_sections", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.HomePageSectionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyHtml")
                        .HasColumnType("text");

                    b.Property<int>("HomePageSectionId")
                        .HasColumnType("integer");

                    b.Property<string>("JsonPayload")
                        .HasColumnType("text");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("HomePageSectionId", "LanguageId")
                        .IsUnique();

                    b.ToTable("home_page_section_translations", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRtl")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.MailSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("mail_settings", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("media_files", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Kind", "Name");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Anchor")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LinkType")
                        .HasColumnType("integer");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentMenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetPageId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("ParentMenuItemId");

                    b.HasIndex("TargetPageId");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.MenuItemTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("MenuItemId", "LanguageId")
                        .IsUnique();

                    b.ToTable("menu_item_translations", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PageType")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Slug")
                        .IsUnique();

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.PageComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponentItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentItemId");

                    b.HasIndex("PageId", "ComponentItemId")
                        .IsUnique();

                    b.ToTable("page_components", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.PageTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PageId", "LanguageId")
                        .IsUnique();

                    b.ToTable("page_translations", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.SeoMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OgDescription")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("OgImageMediaId")
                        .HasColumnType("integer");

                    b.Property<string>("OgTitle")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("Robots")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("OgImageMediaId");

                    b.HasIndex("PageId", "LanguageId")
                        .IsUnique();

                    b.ToTable("seo_metadata", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Key")
                        .IsUnique();

                    b.ToTable("site_settings", (string)null);
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.Company", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Language", "DefaultLanguage")
                        .WithMany()
                        .HasForeignKey("DefaultLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultLanguage");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.CompanyLanguage", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Company", "Company")
                        .WithMany("CompanyLanguages")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Europiyum.Cms.Domain.Entities.Language", "Language")
                        .WithMany("CompanyLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.ComponentItem", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Company", "Company")
                        .WithMany("Components")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Europiyum.Cms.Domain.Entities.ComponentType", "ComponentType")
                        .WithMany("Items")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Europiyum.Cms.Domain.Entities.MediaFile", "PrimaryMedia")
                        .WithMany()
                        .HasForeignKey("PrimaryMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("ComponentType");

                    b.Navigation("PrimaryMedia");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.ComponentTranslation", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.ComponentItem", "ComponentItem")
                        .WithMany("Translations")
                        .HasForeignKey("ComponentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Europiyum.Cms.Domain.Entities.Language", "Language")
                        .WithMany("ComponentTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComponentItem");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.FormDefinition", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Company", "Company")
                        .WithMany("FormDefinitions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.FormField", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.FormDefinition", "FormDefinition")
                        .WithMany("Fields")
                        .HasForeignKey("FormDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormDefinition");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.FormSubmission", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.FormDefinition", "FormDefinition")
                        .WithMany("Submissions")
                        .HasForeignKey("FormDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormDefinition");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.HomePageSection", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Company", "Company")
                        .WithMany("HomePageSections")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Europiyum.Cms.Domain.Entities.ComponentItem", "LinkedComponentItem")
                        .WithMany("HomePageSections")
                        .HasForeignKey("LinkedComponentItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("LinkedComponentItem");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.HomePageSectionTranslation", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.HomePageSection", "HomePageSection")
                        .WithMany("Translations")
                        .HasForeignKey("HomePageSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Europiyum.Cms.Domain.Entities.Language", "Language")
                        .WithMany("HomePageSectionTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HomePageSection");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.MailSetting", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Company", "Company")
                        .WithOne("MailSetting")
                        .HasForeignKey("Europiyum.Cms.Domain.Entities.MailSetting", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.MediaFile", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Company", "Company")
                        .WithMany("MediaFiles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.Menu", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Company", "Company")
                        .WithMany("Menus")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Menu", "Menu")
                        .WithMany("Items")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Europiyum.Cms.Domain.Entities.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentMenuItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Europiyum.Cms.Domain.Entities.Page", "TargetPage")
                        .WithMany()
                        .HasForeignKey("TargetPageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Menu");

                    b.Navigation("Parent");

                    b.Navigation("TargetPage");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.MenuItemTranslation", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Language", "Language")
                        .WithMany("MenuItemTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Europiyum.Cms.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany("Translations")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.Page", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Company", "Company")
                        .WithMany("Pages")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.PageComponent", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.ComponentItem", "ComponentItem")
                        .WithMany("PageComponents")
                        .HasForeignKey("ComponentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Europiyum.Cms.Domain.Entities.Page", "Page")
                        .WithMany("PageComponents")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentItem");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.PageTranslation", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Language", "Language")
                        .WithMany("PageTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Europiyum.Cms.Domain.Entities.Page", "Page")
                        .WithMany("Translations")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.SeoMetadata", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Europiyum.Cms.Domain.Entities.MediaFile", "OgImageMedia")
                        .WithMany()
                        .HasForeignKey("OgImageMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Europiyum.Cms.Domain.Entities.Page", "Page")
                        .WithMany("SeoEntries")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("OgImageMedia");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.SiteSetting", b =>
                {
                    b.HasOne("Europiyum.Cms.Domain.Entities.Company", "Company")
                        .WithMany("SiteSettings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.Company", b =>
                {
                    b.Navigation("CompanyLanguages");

                    b.Navigation("Components");

                    b.Navigation("FormDefinitions");

                    b.Navigation("HomePageSections");

                    b.Navigation("MailSetting");

                    b.Navigation("MediaFiles");

                    b.Navigation("Menus");

                    b.Navigation("Pages");

                    b.Navigation("SiteSettings");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.ComponentItem", b =>
                {
                    b.Navigation("HomePageSections");

                    b.Navigation("PageComponents");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.ComponentType", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.FormDefinition", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.HomePageSection", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.Language", b =>
                {
                    b.Navigation("CompanyLanguages");

                    b.Navigation("ComponentTranslations");

                    b.Navigation("HomePageSectionTranslations");

                    b.Navigation("MenuItemTranslations");

                    b.Navigation("PageTranslations");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.MenuItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Europiyum.Cms.Domain.Entities.Page", b =>
                {
                    b.Navigation("PageComponents");

                    b.Navigation("SeoEntries");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
